<?xml version="1.0"?>
<package format="2">
  <name>driver</name>
  <version>0.1.0</version>
  <description>Reach Alpha 5 serial driver, with a simulated arm for running without hardware.</description>
  <maintainer email="bolin@todo.todo">nknight</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>bx_msgs</depend>
  <depend>roscpp</depend>
  <depend>rospy</depend>
  <depend>roslib</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>params</depend>
</package>
