<?xml version="1.0"?>
<package format="2">
  <name>bringup</name>
  <version>0.1.0</version>
  <description>Every config file and the one launch file.</description>
  <maintainer email="bolin@todo.todo">nknight</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>description</exec_depend>
  <exec_depend>driver</exec_depend>
  <exec_depend>cloud</exec_depend>
  <exec_depend>planner</exec_depend>
  <exec_depend>executor</exec_depend>
  <exec_depend>task</exec_depend>
  <exec_depend>viz</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>foxglove_bridge</exec_depend>
  <exec_depend>rosbag</exec_depend>
</package>
